const demoTracks = [
  { id: 1, title: 'Night Swim', artist: 'Sora Fields', album: 'After Hours', duration: '3:42', art: 'art-lime', icon: '✦', mood: 'Chill', src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 2, title: 'Glass Houses', artist: 'The Polaroids', album: 'Soft Focus', duration: '4:08', art: 'art-coral', icon: '◒', mood: 'Focus', src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 3, title: 'Solstice', artist: 'Mira Vale', album: 'Open Air', duration: '3:19', art: 'art-lavender', icon: '☼', mood: 'Energy', src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 4, title: 'Blue Hour', artist: 'Low Season', album: 'The Long Way Home', duration: '5:01', art: 'art-coral', icon: '✺', mood: 'Chill', src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' }
];
const state = { tracks: [...demoTracks], queue: [], current: null, playing: false, repeat: false };
const $ = (id) => document.getElementById(id);
const audio = $('audio');
const formatTime = (seconds) => Number.isFinite(seconds) ? `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}` : '0:00';
function showToast(message) { const toast = $('toast'); toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2200); }
function renderTracks(filter = '') { const query = filter.toLowerCase(); const tracks = state.tracks.filter((track) => `${track.title} ${track.artist} ${track.album} ${track.mood}`.toLowerCase().includes(query)); $('trackList').innerHTML = tracks.length ? tracks.map((track) => `<article class="track-row"><div class="track-art ${track.art}">${track.icon}</div><div class="track-meta"><strong>${track.title}</strong><span>${track.artist} · ${track.album}</span></div><span class="track-duration">${track.duration}</span><button class="add-button" data-add="${track.id}" aria-label="Add ${track.title} to queue">+</button></article>`).join('') : '<p class="empty-state">No tracks match that search yet.</p>'; }
function renderQueue() { $('queueCount').textContent = state.queue.length; $('queueList').innerHTML = state.queue.length ? state.queue.map((track, index) => `<div class="queue-item"><span class="queue-number">${String(index + 1).padStart(2, '0')}</span><div class="queue-meta"><strong>${track.title}</strong><span>${track.artist}</span></div><button class="remove-button" data-remove="${track.id}" aria-label="Remove ${track.title}">×</button></div>`).join('') : '<p class="empty-state">Your queue is quiet.<br />Add a song to start listening.</p>'; }
function setCurrent(track, autoplay = false) { state.current = track; audio.src = track.src; $('nowTitle').textContent = track.title; $('nowArtist').textContent = `${track.artist} · ${track.album}`; $('miniArt').textContent = track.icon; $('miniArt').className = `mini-art ${track.art}`; if (autoplay) audio.play().then(() => updatePlayButton()).catch(() => showToast('Press play to start this track')); }
function playTrack(track) { setCurrent(track, true); if (!state.queue.some((item) => item.id === track.id)) state.queue.push(track); renderQueue(); }
function updatePlayButton() { state.playing = !audio.paused; $('playButton').textContent = state.playing ? 'Ⅱ' : '▶'; $('playButton').setAttribute('aria-label', state.playing ? 'Pause' : 'Play'); }
function playNext() { const index = state.current ? state.queue.findIndex((track) => track.id === state.current.id) : -1; const next = state.queue[index + 1] || (state.repeat && state.current) || state.queue[0]; if (next) playTrack(next); }
$('trackList').addEventListener('click', (event) => { const add = event.target.closest('[data-add]'); if (!add) return; const track = state.tracks.find((item) => item.id === Number(add.dataset.add)); if (track && !state.queue.some((item) => item.id === track.id)) { state.queue.push(track); renderQueue(); showToast(`${track.title} added to queue`); } else showToast('That song is already in your queue'); });
$('queueList').addEventListener('click', (event) => { const remove = event.target.closest('[data-remove]'); if (!remove) return; state.queue = state.queue.filter((track) => track.id !== Number(remove.dataset.remove)); renderQueue(); });
$('searchInput').addEventListener('input', (event) => renderTracks(event.target.value));
$('playButton').addEventListener('click', () => { if (!state.current) { const track = state.queue[0] || state.tracks[0]; playTrack(track); } else if (audio.paused) audio.play(); else audio.pause(); updatePlayButton(); });
$('nextButton').addEventListener('click', playNext);
$('prevButton').addEventListener('click', () => { audio.currentTime = 0; if (state.current) audio.play(); });
$('shuffleButton').addEventListener('click', () => { state.queue = [...state.tracks].sort(() => Math.random() - .5); renderQueue(); playTrack(state.queue[0]); });
$('clearQueue').addEventListener('click', () => { state.queue = []; renderQueue(); showToast('Queue cleared'); });
$('likeButton').addEventListener('click', (event) => { event.currentTarget.classList.toggle('liked'); event.currentTarget.textContent = event.currentTarget.classList.contains('liked') ? '♥' : '♡'; });
$('repeatButton').addEventListener('click', (event) => { state.repeat = !state.repeat; event.currentTarget.style.color = state.repeat ? 'var(--accent)' : ''; showToast(state.repeat ? 'Repeat on' : 'Repeat off'); });
$('volume').addEventListener('input', (event) => { audio.volume = event.target.value; });
$('volumeButton').addEventListener('click', () => { audio.muted = !audio.muted; $('volumeButton').textContent = audio.muted ? '◌' : '◖'; });
$('progress').addEventListener('input', (event) => { if (audio.duration) audio.currentTime = (event.target.value / 100) * audio.duration; });
audio.addEventListener('timeupdate', () => { $('currentTime').textContent = formatTime(audio.currentTime); $('duration').textContent = formatTime(audio.duration); $('progress').value = audio.duration ? (audio.currentTime / audio.duration) * 100 : 0; });
audio.addEventListener('play', updatePlayButton); audio.addEventListener('pause', updatePlayButton); audio.addEventListener('ended', playNext);
$('importButton').addEventListener('click', () => $('fileInput').click());
$('fileInput').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const track = { id: Date.now(), title: file.name.replace(/\.[^/.]+$/, ''), artist: 'Local file', album: 'Imported audio', duration: '--:--', art: 'art-lime', icon: '♫', mood: 'Local', src: URL.createObjectURL(file) }; state.tracks.unshift(track); renderTracks($('searchInput').value); playTrack(track); showToast('Local track loaded'); });
$('urlButton').addEventListener('click', () => { const url = prompt('Paste a direct audio file URL'); if (!url) return; let title = url.split('/').pop().split('?')[0] || 'Remote track'; title = decodeURIComponent(title).replace(/\.[^/.]+$/, ''); const track = { id: Date.now(), title, artist: 'Remote audio', album: 'From URL', duration: '--:--', art: 'art-lavender', icon: '↗', mood: 'Remote', src: url }; state.tracks.unshift(track); renderTracks($('searchInput').value); playTrack(track); showToast('Remote track loaded'); });
$('newPlaylist').addEventListener('click', () => { const name = prompt('Name your playlist'); if (name) { const button = document.createElement('button'); button.className = 'playlist-link'; button.textContent = name; $('playlistList').appendChild(button); showToast('Playlist created'); } });
renderTracks(); renderQueue(); audio.volume = .8;
